# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T7D1qDwj_Si11Y6t35rDO9CzhmCw7wgW
"""


from datetime import datetime
import requests
import pandas as pd

url = "https://jobicy.com/api/v2/remote-jobs?industry=dev"

response = requests.get(url, timeout=20)
print("Status code:", response.status_code)

data = response.json()
rows = []

jobs = data.get("jobs", [])
print("Aantal gevonden vacatures:", len(jobs))

scrape_time = datetime.now().isoformat()
for job in jobs:
    rows.append({
        "job_title": job.get("jobTitle"),
        "company": job.get("companyName"),
        "location": job.get("jobGeo"),
        "job_type": job.get("jobType"),
        "publication_date": job.get("pubDate"),
        "job_url": job.get("url"),
        "scraped_at": scrape_time,
    })

df = pd.DataFrame(rows)


import os

filename = "jobicy_dev_jobs.csv"

if os.path.exists(filename):
    # File already exists → append without writing headers again
    df.to_csv(filename, mode="a", header=False, index=False)
else:
    # First run → create file with headers
    df.to_csv(filename, index=False)

print(f"Appended {len(df)} rows — total file now has historical data")

# Check what your DataFrame looks like right now
print(f"Columns: {list(df.columns)}")
print(f"Data types:\n{df.dtypes}")
print(f"\nFirst 3 rows:")


# Final check
print(f"Rows: {len(df)}")
print(f"Columns: {list(df.columns)}")
print(f"Data types:\n{df.dtypes}")
print(f"\nSample:")


# Install Supabase client

# Imports
from supabase import create_client
from datetime import datetime

# ✅ Your Supabase credentials
import os

SUPABASE_URL = os.environ["https://kljkpojeelgtqthvqsia.supabase.co"]
SUPABASE_KEY = os.environ["sb_publishable_BaKGlZzewb2u2E3fbk9YsQ_20fDZdpJ"]

# Create Supabase client
supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

# Timestamp for auditing
scrape_time = datetime.utcnow().isoformat()

# Convert DataFrame to Supabase rows
rows = []

for _, row in df.iterrows():
    rows.append({
        "job_title": row.get("job_title"),
        "company": row.get("company"),
        "location": row.get("location"),
        "job_type": row.get("job_type"),
        "publication_date": row.get("publication_date"),
        "job_url": row.get("job_url"),
        "scraped_at": scrape_time
    })

# Insert into Supabase
result = supabase.table("jobicy_dev_jobs").insert(rows).execute()

print(f"✅ Inserted {len(rows)} rows into Supabase")
